version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: yarn install
      - run: CI=true yarn run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: yarn install
      - run: yarn run test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hellloooo!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
