version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    stpes:
      - checkout
      - run: echo 'yarn install'
      - run: yarn
      - run: CI=true yarn run build
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo 'testing stuff'
      - run: yarn
      - run: yarn test
  hithere:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo 'hello there'
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: yarn test
